# # image: node:latest
# image: rambabusaravanan/firebase

# stages:
#   - test
#   - build
#   - deploy

# before_script:
#   - npm -g config set user root
#   - npm install -g firebase-tools
#   - npm install

# # cache:
#   # paths:
#     # - node_modules/
#     # - functions/node_modules/
# cache: 
#   paths:
#     - node_modules/     
#   key: "$CI_BUILD_REPO"

# test:
#   stage: test
#   only:
#     - dev
#   script:
#     - echo "Running tests"
#     - npm run test

# # build:
# #   stage: build
# #   script:
# #     - echo "Building the app"
# #     - npm run build

# # deploy:
# #   stage: deploy
# #   environment: Production
# #   only:
# #     - master
# #   script:
# #     - echo "Building the app"
# #     - npm run build
# #     # - npm run deploy
# #     - firebase use default --token $FIREBASE_TOKEN
# #     - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
# #     # - firebase use default --token $FIREBASE_DEPLOY_KEY
# #     # - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --only hosting --token $FIREBASE_DEPLOY_KEY
